"""initial

Revision ID: a6499f9a1da9
Revises:
Create Date: 2026-01-23 14:28:42.957676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6499f9a1da9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subtitlecache',
    sa.Column('video_url', sa.String(length=500), nullable=False),
    sa.Column('video_id', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('output_format', sa.String(length=20), nullable=False),
    sa.Column('subtitle_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_url', 'language', 'output_format', name='uq_subtitle_cache_lookup')
    )
    op.create_index(op.f('ix_subtitlecache_language'), 'subtitlecache', ['language'], unique=False)
    op.create_index(op.f('ix_subtitlecache_output_format'), 'subtitlecache', ['output_format'], unique=False)
    op.create_index(op.f('ix_subtitlecache_video_id'), 'subtitlecache', ['video_id'], unique=False)
    op.create_index(op.f('ix_subtitlecache_video_url'), 'subtitlecache', ['video_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subtitlecache_video_url'), table_name='subtitlecache')
    op.drop_index(op.f('ix_subtitlecache_video_id'), table_name='subtitlecache')
    op.drop_index(op.f('ix_subtitlecache_output_format'), table_name='subtitlecache')
    op.drop_index(op.f('ix_subtitlecache_language'), table_name='subtitlecache')
    op.drop_table('subtitlecache')
    # ### end Alembic commands ###
